local dap = require('dap-go')
dap.setup()

vim.keymap.set('n', '<F5>', function() require('dap').continue() end, { desc = "[DAP] continue" })
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, { desc = "[DAP] step over" })
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, { desc = "[DAP] step into" })
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end, { desc = "[DAP] step out" })
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end, { desc = "[DAP] toggle breakpoint" })
vim.keymap.set('n', '<Leader>B', function() require('dap').set_breakpoint() end, { desc = "[DAP] set breakpoint" })
vim.keymap.set('n', '<Leader>lp', function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end, { desc = "[DAP] set breakpoint log point" })
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end, { desc = "[DAP] open repl" })
vim.keymap.set('n', '<Leader>dl', function() require('dap').run_last() end, { desc = "[DAP] run last" })
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
  require('dap.ui.widgets').hover()
end, { desc = "[DAP] hover" })
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
  require('dap.ui.widgets').preview()
end, { desc = "[DAP] preview" })
vim.keymap.set('n', '<Leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end, { desc = "[DAP] frames" })
vim.keymap.set('n', '<Leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end, { desc = "[DAP] scopes" })
vim.keymap.set('n', '<Leader>dt', function() require('dap').terminate() end, { desc = "[DAP] terminate" })
require("dapui").setup()
vim.keymap.set('n', '<Leader>du', function() require('dapui').toggle() end, { desc = "[DAP] toggle ui" })
